version: "3.8"

services:
  db_service:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db_service