# Generated by Django 4.2.7 on 2023-11-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("slido_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="visitor",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="slido_app.visitor",
            ),
        ),
    ]
